version: '2'
services:
  rest-backend:
    container_name: monolith
    build:
      context: backend
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./backend/m2:/root/.m2
    depends_on:
      - backend-postgres
  s3:
    image: minio/minio:RELEASE.2023-04-07T05-28-58Z
    restart: "unless-stopped"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    ports:
      - "127.0.0.1:9000:9000"
      - "9001:9001"
  backend-postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: ooc
      PGDATA: /data/postgres
    volumes:
      - ./backend/postgres-data:/data/postgres
    ports:
      - "5432:5432"

  # front:
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"